### ISSUE TITLE
Batch renaming NLA tracks to all the same name?

### ISSUE THREAD

**Issue by kitaedesigns** [tinmanjuggernaut/blender-pushdownall#1]
This plugin seems to correctly push down all animations to NLA strips but is it possible to name them all the same name? For GLTF to play multiple animations they all need to have the same name whereas this plugin creates NLA strips with numbered names.

**Comment by TokisanGames** [comment]
In blender, animations are actions, which all have unique names. This script optionally renames the actions. It does nothing with the NLA tracks. It calls the built in push down function, and that's it. No naming. It's exactly the same as clicking the push down button over and over. 

After pushing down, I export my models to Godot as GLTF. All of the imported animations have unique names, matching the original animations in blender. 

What is your destination application?

**Comment by kitaedesigns** [comment]
Destination application is modelviewer in web. I test in modelviewer.dev/editor and glb’s exported using pushdown will have an export per NLA track name due to the name’s being different.

Best,

Kitae Kim

Third Axis
www.thirdaxis.io


________________________________

**Comment by TokisanGames** [comment]
I wonder if this is a limitation of modelviewer, as Godot reads all the animations fine. I haven't tried any other apps. Do you have a link to documentation that shows GLTF requires nlatracks have the same name? I won't change it in the repository without that, as it is not the standard behavior of Blender when pushing down tracks. Blender autoincrements them. However, for your version, you can rename tracks by making these changes:

Add in this for loop above line 56 in `PushDownAll.py`, then save and restart blender. This will name all tracks to `NlaTrack`. You can set the name to whatever you like. 
```
        for i, track in enumerate(bpy.context.active_object.animation_data.nla_tracks):
            track.name = "NlaTrack"
```

It should look exactly like this in context. Note the indentation carefully.

```
        ...
            bpy.context.space_data.ui_mode = 'ACTION'
            bpy.ops.action.push_down()
            
        for i, track in enumerate(bpy.context.active_object.animation_data.nla_tracks):
            track.name = "NlaTrack"

        print("Pushed down %d animations." % len(context.scene.animations.data) )
        ...
```

**Comment by TokisanGames** [comment]
Solution provided. Closing ticket.
